[package]
name = "chat_web_socket_server"
version = "0.1.0"
edition = "2024"
description = "WebSocket server for the Krabby chat implementation"
repository = "https://github.com/KrabbyHQ/chat__web_socket_server"
homepage = "https://github.com/KrabbyHQ/chat__web_socket_server"
license = "MIT"

[dependencies]
anyhow = "1.0.102"
axum = { version = "0.8.8", features = ["ws"] }
chrono = { version = "0.4.44", features = ["serde", "clock"] }
config = "0.15.19"
dotenvy = "0.15.7"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "json", "time"] }
uuid = { version = "1.21.0", features = ["v4"] }

[dev-dependencies]
axum-test = "18.7.0"
tokio = { version = "1.49.0", features = ["full", "macros"] }
